server {
    listen 80;

    server_name taskcy.online www.taskcy.online;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Static files
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
        try_files $uri /index.html;
    }

    error_page 404 /index.html;
}
