services:
  proxy:
    image: nginx:alpine
    container_name: taskcy-proxy
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - /etc/letsencrypt:/etc/letsencrypt
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl.conf:/etc/nginx/ssl.conf
      - ./proxy/conf.d:/etc/nginx/conf.d
    networks:
      - taskcy_app_proxy
    mem_limit: 128m
    cpus: 0.25

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
        WEB_URL: ${WEB_URL}
    container_name: taskcy-fe
    image: taskcy-fe
    restart: unless-stopped
    networks:
      - taskcy_app_proxy
    depends_on:
      - api
    mem_limit: 256m
    cpus: 0.50

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taskcy-be
    image: taskcy-be
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      - db
    networks:
      - taskcy_app_be
      - taskcy_app_proxy
    command: >
      sh -c "yarn run migration:run && yarn start"
    mem_limit: 512m
    cpus: 0.75

  db:
    image: postgres:15
    container_name: taskcy-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - taskcy_app_be
    mem_limit: 768m
    cpus: 0.75


  adminer:
    image: adminer:5.2.1-standalone
    container_name: taskcy-adminer
    restart: always
    depends_on:
      - db
    networks:
      - taskcy_app_be
      - taskcy_app_proxy
    mem_limit: 128m
    cpus: 0.25

volumes:
  db_data:

networks:
  taskcy_app_be:
    driver: bridge
  taskcy_app_proxy:
    external: true