services:
  proxy:
    image: nginx:alpine
    container_name: taskcy-proxy
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - taskcy_app_proxy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: taskcy-fe
    image: taskcy-fe
    restart: unless-stopped
    networks:
      - taskcy_app_proxy
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taskcy-be
    image: taskcy-be
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - taskcy_app_be
      - taskcy_app_proxy

  db:
    image: postgres:15
    container_name: taskcy-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - taskcy_app_be

volumes:
  db_data:

networks:
  taskcy_app_be:
    driver: bridge
  taskcy_app_proxy:
    external: true