name: "Deploy to Ionos"

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: ${{ github.ref_name }}
    env:
      PORT: ${{ vars.PORT }}
      API_URL: ${{ vars.API_URL }}
      WEB_URL: ${{ vars.WEB_URL }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_PORT: ${{ vars.DB_PORT }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and deploy
        run: |
          # Stop services
          docker compose down

          # Check network
          docker network inspect taskcy_app_proxy || docker network create taskcy_app_proxy

          # Start services
          docker compose up -d --build
